name: Build and Release Executable

# Déclenchement du workflow
on:
  workflow_dispatch:  # Lancement manuel
  pull_request:       # Déclenchement au merge d'une PR sur `main`
    branches:
      - main

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Python et construire l'exécutable avec PyInstaller
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12.4'  # Version de Python à utiliser
          pyinstaller_ver: '==5.13.2'
          spec: './recup_cfe.py'  # Script principal à packager
          requirements: './requirements.txt'  # Fichier des dépendances
          upload_exe_with_name: 'Telechargement_CFE.exe'  # Nom de l'exécutable
          options: --onefile, --name "Telechargement_CFE", --windowed


      # Étape 3 : Créer ou mettre à jour une Release GitHub
      - name: Create or Update Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v1.0.0"  # Nom de la release
          release_name: "Téléchargement CFE - Release"  # Nom lisible de la release
          body: |
            Voici la dernière version de l'exécutable `Téléchargement CFE`.
            Téléchargez le fichier ci-dessous pour commencer.
          draft: false  # Si `true`, la release sera un brouillon
          prerelease: false

      # Étape 4 : Télécharger et ajouter l'exécutable à la Release
      - name: Upload Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/Telechargement_CFE.exe  # Chemin vers le fichier
          asset_name: Telechargement_CFE.exe  # Nom du fichier dans la release
          asset_content_type: application/octet-stream
