# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Construire l'exécutable avec PyInstaller
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12.4'  # Version de Python à utiliser
          pyinstaller_ver: '==5.13.2'
          spec: './recup_cfe.py'
          requirements: './requirements.txt'  # Fichier des dépendances à installer
          upload_exe_with_name: 'Telechargement_CFE.exe'  # Nom de l'exécutable à téléverser
          options: --onefile, --name "Telechargement_CFE", --windowed
