name: Build and Release Executable

# Déclenchement du workflow
on:
  workflow_dispatch:  # Lancement manuel
  pull_request:       # Déclenchement au merge d'une PR sur `main`
    branches:
      - main
  push:
    tags:
      - 'v*.*.*'  # Déclenchement lors de la poussée de tags correspondant au format vX.Y.Z

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Python et construire l'exécutable avec PyInstaller
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12.4'
          pyinstaller_ver: '==5.13.2'
          spec: './recup_cfe.py'
          requirements: './requirements.txt'
          upload_exe_with_name: 'Telechargement_CFE.exe'
          options: --onefile, --name "Telechargement_CFE", --windowed

      # Étape 3 : Extraire la version du tag (uniquement pour les push sur les tags)
      - name: Extract tag version
        if: startsWith(github.ref, 'refs/tags/')  # Se déclenche uniquement si c'est un push sur un tag
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"  # Extraction du tag
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV  # Sauvegarde la version dans une variable d'environnement

      # Étape 4 : Créer ou mettre à jour une Release GitHub
      - name: Create or Update Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}  # Utilisation du tag extrait
          release_name: "Téléchargement CFE - Release"
          body: |
            Voici la dernière version de l'exécutable `Téléchargement CFE` (version ${{ env.TAG_NAME }}).
            Téléchargez le fichier ci-dessous pour commencer.
          draft: false
          prerelease: false

      # Étape 5 : Télécharger et ajouter l'exécutable à la Release
      - name: Upload Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/Telechargement_CFE.exe
          asset_name: Telechargement_CFE.exe
          asset_content_type: application/octet-stream
