name: Build and Release Executable

# Déclenchement du workflow
on:
  workflow_dispatch:  # Lancement manuel
  pull_request:       # Déclenchement au merge d'une PR sur `main`
    branches:
      - main

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Python et construire l'exécutable avec PyInstaller
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12.4'
          pyinstaller_ver: '==5.13.2'
          spec: './recup_cfe.py'
          requirements: './requirements.txt'
          upload_exe_with_name: 'Telechargement_CFE.exe'
          options: --onefile, --name "Telechargement_CFE", --windowed

      # Étape 3 : Vérifier et supprimer le tag existant
      - name: Delete existing tag if present
        run: |
          TAG_NAME="v1.0.0"
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            git push --delete origin "$TAG_NAME"
            git tag -d "$TAG_NAME"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Étape 4 : Créer ou mettre à jour une Release GitHub
      - name: Create or Update Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v1.0.0"
          release_name: "Téléchargement CFE - Release"
          body: |
            Voici la dernière version de l'exécutable `Téléchargement CFE`.
            Téléchargez le fichier ci-dessous pour commencer.
          draft: false
          prerelease: false

      # Étape 5 : Télécharger et ajouter l'exécutable à la Release
      - name: Upload Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/Telechargement_CFE.exe
          asset_name: Telechargement_CFE.exe
          asset_content_type: application/octet-stream
